# -*- coding: utf-8 -*-
"""
Compute Experiment Configuration

Static configuration for the Compute experiment, generated from
csvs/instrument_config.csv design specification.

This file is NOT generated at runtime - it is pre-generated by the agent
based on the CSV specification and resource allocation rules.

Resource Allocation Summary:
    Synchronous Sweep Terminals (must be on same instrument - 5270B):
        OUT1, OUT2, X1, IMEAS → 5270B HR SMUs (channels 1-4)
    
    Fixed I terminals (6):
        TRIM1, TRIM2, F11, F12 → 5270B channels 5-8
        X2, KGAIN1, KGAIN2, IREFP → 4156B channels 1-4
    
    GNDU terminal (1): VSS
        → 5270B GNDU
    
    VSU terminals (2): VDD, VCC
        → 4156B VSU21, VSU22
    
    PPG terminal (1): ERASE_PROG
        → 81104A Channel 1 (DC mode only - VCC or 0V, never triggered)

Compliance Settings:
    - Voltage sources: 1mA compliance
    - Current sources: 2V compliance (limits negative voltage)
    - Current direction: "pulled" (positive = into IV meter)

Enable Sequence:
    1. PPG (DC mode - set voltage but don't trigger)
    2. Voltage supplies (VDD, VCC via VSU)
    3. Fixed current supplies (KGAIN1/2, TRIM1/2, X2, IREFP, F11, F12)
    4. Synchronous sweep (X1, IMEAS with OUT1/OUT2 current measurement)

Synchronous Sweep:
    - X1 and IMEAS are swept synchronously
    - OUT1 and OUT2 have VDD applied, current measured during sweep
    - All four (OUT1, OUT2, X1, IMEAS) must be on 5270B for sync operation
"""

from .resource_types import (
    MeasurementType, InstrumentType, TerminalConfig, ExperimentConfig
)

# ============================================================================
# Compute Experiment Terminal Configurations
# ============================================================================

COMPUTE_TERMINALS = {
    # ------------------------------------
    # Synchronous Sweep Terminals - All on 5270B HR SMUs for sync operation
    # ------------------------------------
    "OUT1": TerminalConfig(
        terminal="OUT1",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=1,
        description="Output 1 - 5270B HR SMU - sync sweep (apply VDD, measure I)"
    ),
    "OUT2": TerminalConfig(
        terminal="OUT2",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=2,
        description="Output 2 - 5270B HR SMU - sync sweep (apply VDD, measure I)"
    ),
    "X1": TerminalConfig(
        terminal="X1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=3,
        description="X1 current - 5270B HR SMU - sync sweep source"
    ),
    "IMEAS": TerminalConfig(
        terminal="IMEAS",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=4,
        description="Measurement current - 5270B HR SMU - sync sweep source"
    ),
    
    # ------------------------------------
    # Fixed I Terminals on 5270B - MP SMUs (channels 5-8)
    # ------------------------------------
    "TRIM1": TerminalConfig(
        terminal="TRIM1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=5,
        description="Trim current 1 - 5270B MP SMU - linked with TRIM2"
    ),
    "TRIM2": TerminalConfig(
        terminal="TRIM2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=6,
        description="Trim current 2 - 5270B MP SMU - linked with TRIM1"
    ),
    "F11": TerminalConfig(
        terminal="F11",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=7,
        description="F11 current - 5270B MP SMU - fixed current sweep parameter"
    ),
    "F12": TerminalConfig(
        terminal="F12",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=8,
        description="F12 current - 5270B MP SMU - fixed current sweep parameter"
    ),
    
    # ------------------------------------
    # Fixed I Terminals on 4156B - SMUs (channels 1-4)
    # ------------------------------------
    "X2": TerminalConfig(
        terminal="X2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=1,
        description="X2 current - 4156B SMU - fixed current sweep parameter"
    ),
    "KGAIN1": TerminalConfig(
        terminal="KGAIN1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=2,
        description="KGAIN1 current - 4156B SMU - linked with KGAIN2"
    ),
    "KGAIN2": TerminalConfig(
        terminal="KGAIN2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=3,
        description="KGAIN2 current - 4156B SMU - linked with KGAIN1"
    ),
    "IREFP": TerminalConfig(
        terminal="IREFP",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=4,
        description="Reference current P - 4156B SMU - fixed current sweep parameter"
    ),
    
    # ------------------------------------
    # GNDU Terminal - Ground Unit (5270B only)
    # ------------------------------------
    "VSS": TerminalConfig(
        terminal="VSS",
        measurement_type=MeasurementType.GNDU,
        instrument=InstrumentType.IV5270B,
        channel=0,  # GNDU is channel 0 in our convention
        description="Ground reference - 5270B GNDU"
    ),
    
    # ------------------------------------
    # VSU Terminals - Voltage Source Units
    # ------------------------------------
    "VDD": TerminalConfig(
        terminal="VDD",
        measurement_type=MeasurementType.VSU,
        instrument=InstrumentType.IV4156B,
        channel=21,
        description="Power supply voltage source - 4156B VSU1"
    ),
    "VCC": TerminalConfig(
        terminal="VCC",
        measurement_type=MeasurementType.VSU,
        instrument=InstrumentType.IV4156B,
        channel=22,
        description="VCC voltage source - 4156B VSU2"
    ),
    
    # ------------------------------------
    # PPG Terminal - Pulse Generator (DC Mode Only)
    # ------------------------------------
    "ERASE_PROG": TerminalConfig(
        terminal="ERASE_PROG",
        measurement_type=MeasurementType.PPG,
        instrument=InstrumentType.PG81104A,
        channel=1,
        description="Erase/Program DC voltage - 81104A Channel 1 (DC mode, never triggered)"
    ),
}

# ============================================================================
# Compute Experiment Configuration
# ============================================================================

COMPUTE_CONFIG = ExperimentConfig(
    name="Compute",
    description="Computation mode characterization with synchronous current sweep",
    terminals=COMPUTE_TERMINALS,
    instruments_used=[
        InstrumentType.IV5270B,
        InstrumentType.IV4156B,
        InstrumentType.PG81104A,
    ]
)

# ============================================================================
# Enable Sequence Configuration
# ============================================================================
# Order in which terminals should be enabled during experiment setup

COMPUTE_ENABLE_SEQUENCE = [
    # Step 1: PPG first (DC mode - set voltage but don't trigger)
    {
        "step": 1,
        "name": "PPG DC Bias",
        "terminals": ["ERASE_PROG"],
        "description": "Enable PPG in DC mode (VCC or 0V, no triggering)"
    },
    # Step 2: Voltage supplies
    {
        "step": 2,
        "name": "Voltage Supplies",
        "terminals": ["VDD", "VCC", "VSS"],
        "description": "Enable VSU voltage supplies and ground"
    },
    # Step 3: Fixed current supplies
    {
        "step": 3,
        "name": "Fixed Current Supplies",
        "terminals": ["KGAIN1", "KGAIN2", "TRIM1", "TRIM2", "X2", "IREFP", "F11", "F12"],
        "description": "Enable all fixed current sources at specified values"
    },
    # Step 4: Synchronous sweep terminals
    {
        "step": 4,
        "name": "Synchronous Sweep",
        "terminals": ["OUT1", "OUT2", "X1", "IMEAS"],
        "description": "Execute synchronous sweep with current measurement on OUT1/OUT2"
    },
]

# ============================================================================
# PPG DC Mode Configuration
# ============================================================================
# PPG provides DC voltage only - never triggered for pulses
# All measurements are done in both ERASE (VCC) and PROGRAM (0V) states

COMPUTE_PPG_DC_CONFIG = {
    "ERASE_PROG": {
        "mode": "DC",  # DC mode - no pulses
        "triggered": False,  # Never triggered
        "description": "PPG provides DC bias only, no pulse generation"
    }
}

# PPG states for measurement - all sweeps are done in both states
COMPUTE_PPG_STATES = {
    "ERASE": {
        "voltage": "VCC",  # Uses VCC voltage value
        "description": "ERASE state - PPG at VCC"
    },
    "PROGRAM": {
        "voltage": 0.0,  # 0V
        "description": "PROGRAM state - PPG at 0V"
    },
}

# Order of PPG states for measurement sequence
COMPUTE_PPG_STATE_ORDER = ["ERASE", "PROGRAM"]

# ============================================================================
# Linked Parameter Groups
# ============================================================================
# Parameters that must have the same value

COMPUTE_LINKED_PARAMETERS = {
    "KGAIN": {
        "terminals": ["KGAIN1", "KGAIN2"],
        "description": "KGAIN1 and KGAIN2 always have the same current value"
    },
    "TRIM": {
        "terminals": ["TRIM1", "TRIM2"],
        "description": "TRIM1 and TRIM2 always have the same current value"
    },
}

# ============================================================================
# Synchronous Sweep Configuration
# ============================================================================
# X1 and IMEAS sweep synchronously while measuring OUT1/OUT2 current

COMPUTE_SYNC_SWEEP_CONFIG = {
    "instrument": InstrumentType.IV5270B,
    "sweep_channels": {
        "X1": 3,      # Primary sweep source
        "IMEAS": 4,   # Secondary sweep source (synchronous with X1)
    },
    "measure_channels": {
        "OUT1": 1,    # Apply VDD, measure current
        "OUT2": 2,    # Apply VDD, measure current
    },
    "description": "X1 and IMEAS swept synchronously, OUT1/OUT2 at VDD with current measurement",
    "measurement_mode": 16,  # Multi-channel sweep mode for 5270B
}

# ============================================================================
# Sweep Parameter Lists (User-Provided Values)
# ============================================================================
# These are placeholder lists - user will provide actual values
# Each combination of these values triggers a complete synchronous sweep

COMPUTE_SWEEP_PARAMETERS = {
    # Linked parameters (same value for both terminals in group)
    "KGAIN": {
        "terminals": ["KGAIN1", "KGAIN2"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "KGAIN current values (applied to both KGAIN1 and KGAIN2)"
    },
    "TRIM": {
        "terminals": ["TRIM1", "TRIM2"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "TRIM current values (applied to both TRIM1 and TRIM2)"
    },
    # Independent parameters
    "X2": {
        "terminals": ["X2"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "X2 current values"
    },
    "IREFP": {
        "terminals": ["IREFP"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "IREFP current values"
    },
    "F11": {
        "terminals": ["F11"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "F11 current values"
    },
    "F12": {
        "terminals": ["F12"],
        "values": [],  # User provides list of current values in Amps
        "unit": "A",
        "description": "F12 current values"
    },
}

# ============================================================================
# Synchronous Sweep Source Configuration
# ============================================================================
# Configuration for X1 and IMEAS synchronous sweep

COMPUTE_SYNC_SWEEP_SOURCES = {
    "X1": {
        "start": 20.0e-9,      # Start current in Amps
        "stop": 80e-9,       # Stop current in Amps
        "step": 5e-9,       # Step current in Amps
        "compliance": 2.0,  # Voltage compliance
        "description": "X1 sweep configuration"
    },
    "IMEAS": {
        "start": 0.0,      # Start current in Amps
        "stop": 0.0,       # Stop current in Amps
        "step": 0.0,       # Step current in Amps
        "compliance": 2.0,  # Voltage compliance
        "description": "IMEAS sweep configuration (synchronous with X1)"
    },
}

# ============================================================================
# Helper Dictionaries for Experiment Execution
# ============================================================================

# Terminals grouped by instrument for efficient setup
COMPUTE_BY_INSTRUMENT = {
    InstrumentType.IV5270B: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV5270B
    },
    InstrumentType.IV4156B: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV4156B
    },
    InstrumentType.PG81104A: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.PG81104A
    },
}

# Terminals grouped by measurement type for bias setup
COMPUTE_BY_TYPE = {
    MeasurementType.V: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.V
    ],
    MeasurementType.I: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.I
    ],
    MeasurementType.GNDU: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.GNDU
    ],
    MeasurementType.VSU: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.VSU
    ],
    MeasurementType.PPG: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.PPG
    ],
}

# Terminals that are part of synchronous sweep (must be on same instrument)
COMPUTE_SYNC_SWEEP_TERMINALS = ["OUT1", "OUT2", "X1", "IMEAS"]

# Fixed current terminals (set before sync sweep, iterate through combinations)
COMPUTE_FIXED_CURRENT_TERMINALS = ["KGAIN1", "KGAIN2", "TRIM1", "TRIM2", "X2", "IREFP", "F11", "F12"]

# Pulse generator configuration for ERASE_PROG - DC MODE ONLY
COMPUTE_PULSE_CONFIG = {
    "ERASE_PROG": {
        "mode": "DC",
        "dc_voltage": None,  # Set to VCC value or 0.0 at runtime
        "triggered": False,
        "description": "DC bias only - never triggered"
    }
}

# Sequential measurement pairs (none needed - sync sweep handles this)
COMPUTE_SEQUENTIAL_PAIRS = []

# Default voltage values
COMPUTE_DEFAULTS = {
    "VDD": 1.8,   # Power supply
    "VCC": 5.0,   # VCC default is 5V
}
