# -*- coding: utf-8 -*-
"""
Compute Experiment Configuration

Static configuration for the Compute experiment, generated from
csvs/instrument_config.csv design specification.

This file is NOT generated at runtime - it is pre-generated by the agent
based on the CSV specification and resource allocation rules.

Resource Allocation Summary:
    V terminals (2): OUT2, OUT1
        → IV5270B HR SMUs (channels 1-2)
    
    I terminals (10): TRIM2, F11, TRIM1, F12, X2, X1, KGAIN2, KGAIN1, IREFP, IMEAS
        → IV5270B channels 3-8 (6 channels)
        → IV4156B channels 1-4 (4 channels)
    
    GNDU terminal (1): VSS
        → IV5270B GNDU
    
    VSU terminals (2): VDD, VCC
        → IV4156B VSU21, VSU22
    
    PPG terminal (1): ERASE_PROG
        → PG81104A Channel 1

Note: With VDD and VCC as VSU instead of V, all I terminals now fit
within available SMU channels without resource conflicts.
"""

from .resource_types import (
    MeasurementType, InstrumentType, TerminalConfig, ExperimentConfig
)

# ============================================================================
# Compute Experiment Terminal Configurations
# ============================================================================

COMPUTE_TERMINALS = {
    # ------------------------------------
    # V Terminals - High-Resolution SMUs (priority allocation)
    # ------------------------------------
    "OUT2": TerminalConfig(
        terminal="OUT2",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=1,
        description="Output 2 voltage measurement - HR SMU"
    ),
    "OUT1": TerminalConfig(
        terminal="OUT1",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=2,
        description="Output 1 voltage measurement - HR SMU"
    ),
    
    # ------------------------------------
    # I Terminals - SMU allocation (any SMU)
    # ------------------------------------
    "TRIM2": TerminalConfig(
        terminal="TRIM2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=3,
        description="Trim current 2 - HR SMU"
    ),
    "F11": TerminalConfig(
        terminal="F11",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=4,
        description="F11 current measurement - HR SMU"
    ),
    "TRIM1": TerminalConfig(
        terminal="TRIM1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=5,
        description="Trim current 1 - MP SMU"
    ),
    "F12": TerminalConfig(
        terminal="F12",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=6,
        description="F12 current measurement - MP SMU"
    ),
    "X2": TerminalConfig(
        terminal="X2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=7,
        description="X2 current measurement - MP SMU"
    ),
    "X1": TerminalConfig(
        terminal="X1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV5270B,
        channel=8,
        description="X1 current measurement - MP SMU"
    ),
    "KGAIN2": TerminalConfig(
        terminal="KGAIN2",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=1,
        description="KGAIN2 current measurement - 4156B SMU"
    ),
    "KGAIN1": TerminalConfig(
        terminal="KGAIN1",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=2,
        description="KGAIN1 current measurement - 4156B SMU"
    ),
    "IREFP": TerminalConfig(
        terminal="IREFP",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=3,
        description="Reference current P - 4156B SMU"
    ),
    "IMEAS": TerminalConfig(
        terminal="IMEAS",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=4,
        description="Measurement current - 4156B SMU"
    ),
    
    # ------------------------------------
    # GNDU Terminal - Ground Unit (5270B only)
    # ------------------------------------
    "VSS": TerminalConfig(
        terminal="VSS",
        measurement_type=MeasurementType.GNDU,
        instrument=InstrumentType.IV5270B,
        channel=0,  # GNDU is channel 0 in our convention
        description="Ground reference - 5270B GNDU"
    ),
    
    # ------------------------------------
    # VSU Terminals - Voltage Source Units
    # ------------------------------------
    "VDD": TerminalConfig(
        terminal="VDD",
        measurement_type=MeasurementType.VSU,
        instrument=InstrumentType.IV4156B,
        channel=21,
        description="Power supply voltage source - 4156B VSU1"
    ),
    "VCC": TerminalConfig(
        terminal="VCC",
        measurement_type=MeasurementType.VSU,
        instrument=InstrumentType.IV4156B,
        channel=22,
        description="VCC voltage source - 4156B VSU2"
    ),
    
    # ------------------------------------
    # PPG Terminal - Pulse Generator
    # ------------------------------------
    "ERASE_PROG": TerminalConfig(
        terminal="ERASE_PROG",
        measurement_type=MeasurementType.PPG,
        instrument=InstrumentType.PG81104A,
        channel=1,
        description="Erase/Program pulse - 81104A Channel 1"
    ),
}

# ============================================================================
# Compute Experiment Configuration
# ============================================================================

COMPUTE_CONFIG = ExperimentConfig(
    name="Compute",
    description="Computation mode characterization with voltage and current measurements",
    terminals=COMPUTE_TERMINALS,
    instruments_used=[
        InstrumentType.IV5270B,
        InstrumentType.IV4156B,
        InstrumentType.PG81104A,
    ]
)

# ============================================================================
# Helper Dictionaries for Experiment Execution
# ============================================================================

# Terminals grouped by instrument for efficient setup
COMPUTE_BY_INSTRUMENT = {
    InstrumentType.IV5270B: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV5270B
    },
    InstrumentType.IV4156B: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV4156B
    },
    InstrumentType.PG81104A: {
        name: cfg for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.instrument == InstrumentType.PG81104A
    },
}

# Terminals grouped by measurement type for bias setup
COMPUTE_BY_TYPE = {
    MeasurementType.V: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.V
    ],
    MeasurementType.I: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.I
    ],
    MeasurementType.GNDU: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.GNDU
    ],
    MeasurementType.VSU: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.VSU
    ],
    MeasurementType.PPG: [
        name for name, cfg in COMPUTE_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.PPG
    ],
}

# Pulse generator configuration for ERASE_PROG
COMPUTE_PULSE_CONFIG = {
    "ERASE_PROG": {
        "default_width": "100NS",
        "default_period": "1US",
        "default_vhigh": 5.0,
        "default_vlow": 0.0,
        "default_rise": "10NS",
    }
}

# Sequential measurement pairs (none needed - all channels now have dedicated resources)
COMPUTE_SEQUENTIAL_PAIRS = []
