# -*- coding: utf-8 -*-
"""
Kalman Experiment Settings
==========================

Quick-edit configuration file for the Kalman-style closed-loop experiment
implemented in `experiments/run_kalman.py`.

All currents are specified in Amps.

Key ideas:
- X1, X2, IMEAS are constrained to the same bounds.
- TRIM1/TRIM2 and KGAIN1/KGAIN2 are independent (not linked).
- IMEAS is generated by a reusable test-pattern generator in
  `experiments/imeas_test_pattern.py` using the configuration below.
"""

# ============================================================================
# 1. VOLTAGE SETTINGS
# ============================================================================

VDD_DEFAULT = 1.8   # VDD voltage in volts
VCC_DEFAULT = 5.0   # VCC voltage in volts

# ============================================================================
# 2. CURRENT BOUNDS (APPLY TO X1, X2, IMEAS)
# ============================================================================

# Bounds for X1, X2 and IMEAS (in Amps)
MIN_CURRENT = 0.1e-9   # 0.1 nA
MAX_CURRENT = 100e-9   # 100 nA

# ============================================================================
# 3. TIME STEP
# ============================================================================

# Time step between successive IMEAS points (seconds)
# Used by the IMEAS generation routine and to scale time-dependent
# parameters such as KGAIN2 and F12 below.
TIME_STEP = 0.01  # seconds

# ============================================================================
# 4. REFERENCE / FIXED CURRENTS
# ============================================================================

# IREFP reference current (A)
IREFP_DEFAULT = 100e-9  # 100 nA

# Initial current settings for fixed bias currents (A)
TRIM1_INITIAL = 20e-9
TRIM2_INITIAL = 20e-9
KGAIN1_INITIAL = 25e-9
KGAIN2_PER_SEC = 25e-9           # base KGAIN2 rate (A / s)
KGAIN2_INITIAL = KGAIN2_PER_SEC * TIME_STEP
F11_INITIAL = 100e-9
F12_PER_SEC = 100e-9                # base F12 rate (unitless / s)
F12_INITIAL = F12_PER_SEC * TIME_STEP

# Initial X currents (A) – will be updated during the loop but start here
X1_INITIAL = 50e-9
X2_INITIAL = 50e-9

# ============================================================================
# 5. IMEAS TEST VECTOR GENERATION
# ============================================================================

# Starting IMEAS value (A) – must satisfy MIN_CURRENT <= IMEAS_INITIAL <= MAX_CURRENT
IMEAS_INITIAL = 50e-9

# Number of IMEAS points to generate (including the initial value)
IMEAS_NUM_POINTS = 1001  # Apparently it can hold 34034 measurements

# Optional RNG seed for reproducibility (set to None for non-deterministic runs)
RNG_SEED = 12345

# ---------------------------------------------------------------------------
# Extended IMEAS pattern controls (shared with big_kalman)
# ---------------------------------------------------------------------------

# Absolute hard limits for IMEAS (A). These normally match MIN_CURRENT /
# MAX_CURRENT but are kept separate in case different bounds are desired.
IMEAS_HARD_MIN = 0.5e-9
IMEAS_HARD_MAX = 100e-9

# Maximum allowed absolute change in IMEAS per step (A). Any attempted step
# that exceeds this magnitude will be clipped to this value.
IMEAS_HARD_ROC_MAX = 5e-9  # 5 nA per step

# Soft minimum and maximum IMEAS (A). The deterministic part of the test
# pattern linearly ramps between these two values at the prescribed ROC,
# repeating in a triangle-wave fashion. Noise is applied on top but the final
# values are still clipped to the hard limits above.
IMEAS_SOFT_MIN = 10e-9
IMEAS_SOFT_MAX = 90e-9

# Soft limits for the rate-of-change (ROC) of IMEAS (A per step). When ROC
# cycling is enabled, the magnitude of ROC will sweep between these two
# values in a triangle-wave pattern while the sign is chosen to move IMEAS in
# the correct direction (up when going from soft min to max, down on the way
# back).
IMEAS_SOFT_ROC_MIN = 0.5e-9
IMEAS_SOFT_ROC_MAX = 3e-9

# Sigma of IMEAS noise (A). At each step a Gaussian random value with mean 0
# and this standard deviation is added to IMEAS before clamping to the hard
# limits.
IMEAS_SIGMA = 2e-9

# Sigma of ROC noise (A per step). At each step a Gaussian random value with
# mean 0 and this standard deviation is added to the current ROC value before
# enforcing the hard ROC limit.
ROC_SIGMA = 0

# Whether ROC should cycle between IMEAS_SOFT_ROC_MIN and IMEAS_SOFT_ROC_MAX
# in a triangle-wave fashion. When disabled, a fixed ROC magnitude equal to
# IMEAS_SOFT_ROC_MAX is used (subject to the hard ROC limit).
ROC_CYCLE_ENABLED = True
