# -*- coding: utf-8 -*-
"""
Programmer Experiment Configuration

Static configuration for the Programmer experiment, generated from
csvs/instrument_config.csv design specification.

This file is NOT generated at runtime - it is pre-generated by the agent
based on the CSV specification and resource allocation rules.

Resource Allocation Summary:
    V terminals (3): VDD, VCC, ICELLMEAS
        → IV5270B HR SMUs (channels 1-3)
    
    I terminals (2): IREFP, PROG_IN
        → IV4156B SMUs (channels 1-2)
    
    GNDU terminal (1): VSS
        → IV5270B GNDU
    
    VSU terminal (1): ERASE_PROG
        → IV4156B VSU21
    
    PPG terminal (1): WR_ENB
        → PG81104A Channel 1
    
    COUNTER terminal (1): PROG_OUT
        → CT53230A Channel 1

Note: This experiment has comfortable resource margins. All terminals
can be active simultaneously without resource conflicts.
"""

from .resource_types import (
    MeasurementType, InstrumentType, TerminalConfig, ExperimentConfig
)

# ============================================================================
# Programmer Experiment Terminal Configurations
# ============================================================================

PROGRAMMER_TERMINALS = {
    # ------------------------------------
    # V Terminals - High-Resolution SMUs (priority allocation)
    # ------------------------------------
    "VDD": TerminalConfig(
        terminal="VDD",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=1,
        description="Power supply voltage - HR SMU for precision"
    ),
    "VCC": TerminalConfig(
        terminal="VCC",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=2,
        description="VCC voltage - HR SMU for precision"
    ),
    "ICELLMEAS": TerminalConfig(
        terminal="ICELLMEAS",
        measurement_type=MeasurementType.V,
        instrument=InstrumentType.IV5270B,
        channel=3,
        description="Cell measurement voltage - HR SMU"
    ),
    
    # ------------------------------------
    # I Terminals - SMU allocation
    # ------------------------------------
    "IREFP": TerminalConfig(
        terminal="IREFP",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=1,
        description="Reference current P - 4156B SMU"
    ),
    "PROG_IN": TerminalConfig(
        terminal="PROG_IN",
        measurement_type=MeasurementType.I,
        instrument=InstrumentType.IV4156B,
        channel=2,
        description="Programming input current - 4156B SMU"
    ),
    
    # ------------------------------------
    # GNDU Terminal - Ground Unit (5270B only)
    # ------------------------------------
    "VSS": TerminalConfig(
        terminal="VSS",
        measurement_type=MeasurementType.GNDU,
        instrument=InstrumentType.IV5270B,
        channel=0,  # GNDU is channel 0 in our convention
        description="Ground reference - 5270B GNDU"
    ),
    
    # ------------------------------------
    # VSU Terminal - Voltage Source Unit
    # ------------------------------------
    "ERASE_PROG": TerminalConfig(
        terminal="ERASE_PROG",
        measurement_type=MeasurementType.VSU,
        instrument=InstrumentType.IV4156B,
        channel=21,
        description="Erase/Program voltage source - 4156B VSU1"
    ),
    
    # ------------------------------------
    # PPG Terminal - Pulse Generator
    # ------------------------------------
    "WR_ENB": TerminalConfig(
        terminal="WR_ENB",
        measurement_type=MeasurementType.PPG,
        instrument=InstrumentType.PG81104A,
        channel=1,
        description="Write enable pulse - 81104A Channel 1"
    ),
    
    # ------------------------------------
    # COUNTER Terminal - Frequency Counter
    # ------------------------------------
    "PROG_OUT": TerminalConfig(
        terminal="PROG_OUT",
        measurement_type=MeasurementType.COUNTER,
        instrument=InstrumentType.CT53230A,
        channel=1,
        description="Programming output frequency - 53230A Channel 1"
    ),
}

# ============================================================================
# Programmer Experiment Configuration
# ============================================================================

PROGRAMMER_CONFIG = ExperimentConfig(
    name="Programmer",
    description="Programming mode with pulse generation and frequency measurement",
    terminals=PROGRAMMER_TERMINALS,
    instruments_used=[
        InstrumentType.IV5270B,
        InstrumentType.IV4156B,
        InstrumentType.PG81104A,
        InstrumentType.CT53230A,
    ]
)

# ============================================================================
# Helper Dictionaries for Experiment Execution
# ============================================================================

# Terminals grouped by instrument for efficient setup
PROGRAMMER_BY_INSTRUMENT = {
    InstrumentType.IV5270B: {
        name: cfg for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV5270B
    },
    InstrumentType.IV4156B: {
        name: cfg for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.instrument == InstrumentType.IV4156B
    },
    InstrumentType.PG81104A: {
        name: cfg for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.instrument == InstrumentType.PG81104A
    },
    InstrumentType.CT53230A: {
        name: cfg for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.instrument == InstrumentType.CT53230A
    },
}

# Terminals grouped by measurement type
PROGRAMMER_BY_TYPE = {
    MeasurementType.V: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.V
    ],
    MeasurementType.I: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.I
    ],
    MeasurementType.GNDU: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.GNDU
    ],
    MeasurementType.VSU: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.VSU
    ],
    MeasurementType.PPG: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.PPG
    ],
    MeasurementType.COUNTER: [
        name for name, cfg in PROGRAMMER_TERMINALS.items()
        if cfg.measurement_type == MeasurementType.COUNTER
    ],
}

# Pulse generator configuration for WR_ENB
PROGRAMMER_PULSE_CONFIG = {
    "WR_ENB": {
        "default_width": "100NS",
        "default_period": "1US",
        "default_vhigh": 3.3,
        "default_vlow": 0.0,
        "default_rise": "10NS",
    }
}

# Counter configuration for PROG_OUT
PROGRAMMER_COUNTER_CONFIG = {
    "PROG_OUT": {
        "default_gate_time": 0.1,  # 100ms
        "coupling": "AC",
        "impedance": 1000000,  # 1 MOhm
    }
}

# Sequential measurement pairs (none for this experiment)
PROGRAMMER_SEQUENTIAL_PAIRS = []

